version: "3.8"

services:
  redis-node-1:
    image: redis:7.0
    network_mode: host
    command: |
      bash -c '
      rm -f /data/nodes.conf /data/dump.rdb /data/appendonly.aof
      redis-server --port 7001 \
        --bind 0.0.0.0 \
        --cluster-enabled yes \
        --cluster-config-file nodes.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --protected-mode no
      '
    volumes:
      - ./.redis/node1:/data

  redis-node-2:
    image: redis:7.0
    network_mode: host
    command: |
      bash -c '
      rm -f /data/nodes.conf /data/dump.rdb /data/appendonly.aof
      redis-server --port 7002 \
        --bind 0.0.0.0 \
        --cluster-enabled yes \
        --cluster-config-file nodes.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --protected-mode no
      '
    volumes:
      - ./.redis/node2:/data

  redis-node-3:
    image: redis:7.0
    network_mode: host
    command: |
      bash -c '
      rm -f /data/nodes.conf /data/dump.rdb /data/appendonly.aof
      redis-server --port 7003 \
        --bind 0.0.0.0 \
        --cluster-enabled yes \
        --cluster-config-file nodes.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --protected-mode no
      '
    volumes:
      - ./.redis/node3:/data

  redis-node-4:
    image: redis:7.0
    network_mode: host
    command: |
      bash -c '
      rm -f /data/nodes.conf /data/dump.rdb /data/appendonly.aof
      redis-server --port 7004 \
        --bind 0.0.0.0 \
        --cluster-enabled yes \
        --cluster-config-file nodes.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --protected-mode no
      '
    volumes:
      - ./.redis/node4:/data

  redis-node-5:
    image: redis:7.0
    network_mode: host
    command: |
      bash -c '
      rm -f /data/nodes.conf /data/dump.rdb /data/appendonly.aof
      redis-server --port 7005 \
        --bind 0.0.0.0 \
        --cluster-enabled yes \
        --cluster-config-file nodes.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --protected-mode no
      '
    volumes:
      - ./.redis/node5:/data

  redis-node-6:
    image: redis:7.0
    network_mode: host
    command: |
      bash -c '
      rm -f /data/nodes.conf /data/dump.rdb /data/appendonly.aof
      redis-server --port 7006 \
        --bind 0.0.0.0 \
        --cluster-enabled yes \
        --cluster-config-file nodes.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --protected-mode no
      '
    volumes:
      - ./.redis/node6:/data

  redis-cluster-init:
    image: redis:7.0
    network_mode: host
    command: |
      bash -c '
      sleep 5
      echo "yes" | redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 --cluster-replicas 1
      '
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
